# Fichier de configuration du site √† personnaliser

# Informations du site 
site_name: NSI Terminale 2022-2023
site_description: Cours et TD de l'ann√©e en cours
site_author: "Michael Meyroneinc-condy" 
copyright: 2023 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a> 
site_url: 

# Structure des dossiers :
docs_dir: docs

# Menu de navigation
nav: 
    - Accueil : index.md
    #- Index : progression.md
    #- Test : Notebook.ipynb

    - T1 - Struct. de donn√©es :
      - Structures de donn√©es : StructureDonnees/index_structDonnees.md
      - üìì C4 P.O.O : StructureDonnees/T1_1_Programmation_Orientee_Objet.md
      - üíª T4 POO Exercices : StructureDonnees/T1_2_TD_POO.md
      - üíª TD POO BAC : StructureDonnees/T1_3_BAC_Capytale.md     
      - üìù S4 Sujet POO BAC : StructureDonnees/POO_BAC_correction.md
      - üìì C5 Listes, Piles et Files : StructureDonnees/T2_1_Listes_Piles_et_Files.md
      #- T2_2 BAC - Listes, Piles et Files : StructureDonnees/T2_2_Pile_File_BAC.md
      - üìù S5 BAC Correction - Listes, Piles et Files : StructureDonnees/T2_2_Pile_File_BAC_Correction.md
      - üìì C9 Les dictionnaires : StructureDonnees/T4_1_Dictionnaires.md
      - üìì C10 Les arbres : StructureDonnees/T3_1_arbre.md
      - üìù S10 BAC Les arbres : StructureDonnees/T3_2_arbre_BAC.md


    
    - T2 - Bases de donn√©es :  
      - Base de donn√©es : BasesDonnees/index_bd.md
      - üìì C1 Mod√®le relationnel : BasesDonnees/Modele_Relationnel.md
      - üìì C2 Langage SQL : BasesDonnees/Cours_TP_SQL.md
      - üìù S2 BAC SQL : BasesDonnees/SQL_BAC.md
      - üìù S2 BAC SQL Correction : BasesDonnees/SQL_BAC_correction.md
    
    - T3 - Archi. mat√®rielle :
      - Architecture mat√©rielle et OS : Archi_Materielle/index_archi.md
      - üìì C6 Protocole de routage : Archi_Materielle/T3_1_Routage.md
      #- T3_1 BAC Protocole de routage : Archi_Materielle/T3_1_Routage_BAC.md
      - üìù S6 BAC Correction Protocole de routage : Archi_Materielle/T3_1_Routage_BAC_Correction.md
      - üìì C13 Gestion Processus : Archi_Materielle/T3_2_gestion_processus.md
      - üìù S13 BAC Gestion Processus : Archi_Materielle/T3_3_gestion_processus_BAC.md
    
    - T4 - Prog. :
      - Programmation : Programmation/index_prog.md
      - üìì C3 R√©cursivit√©  :  Programmation/T1_1_Recursivite.md
      
    #   - R√©cursivit√© : Programmation/T4_1_TP_Recursivite_correction.md

    - T5 Algo. : 
      - Algorithmique : Algo/index_algo.md
      - üìì C7 Tri 1√®re : Algo/T5_2_algo_tri.md
      - üìì C8 Diviser pour r√©gner : Algo/T5_3_Diviser_pour_regner.md
      - üìù S8 Diviser pour r√©gner BAC : Algo/T5_4_Diviser_pour_regner_BAC.md
      - üìì C11 Impl√©mentation des arbres binaires : Algo/TP5_5_Implementation_arbres.md
      - üìù S11 Algorithme arbres binaires BAC : Algo/T5_6_algo_arbre_BAC.md
      - üìì C12 Arbres binaires de recherche : StructureDonnees/T3_3_arbre_recherche.md
      - üìù S12 Arbres binaires de recherche BAC : StructureDonnees/T3_4_arbre_recherche_BAC.md
      - k-plus proches voisins : Algo/TP6_1_kppv.md

    
    - BAC üìù:
      #- index_annales.md
      - '2023': 
        - "Epreuves √©crites" : Annales/2023/EE.md
      - '2022': 
        - "Epreuves √©crites" : Annales/2022/EE.md
      - '2021': 
        - "Epreuves √©crites" : Annales/2021/EE.md




    - Annales du Bac E.P. üíª :
      - D√©roulement : epreuve_pratique.md
      - Consigne : divers/Consigne_EP.md
      #- index_annales.md
      - '2022': 
        - "Epreuves pratiques" : Annales/2022/EP.md
        #- "Corrig√©s √©preuves pratiques":
        #  - "Sujet 1" : Annales/Corriges/2022-S01.md
        #  - "Sujet 2" : Annales/Corriges/2022-S02.md
        #  - "Sujet 3" : Annales/Corriges/2022-S03.md
        #  - "Sujet 4" : Annales/Corriges/2022-S04.md
        #  - "Sujet 5" : Annales/Corriges/2022-S05.md
        #  - "Sujet 6" : Annales/Corriges/2022-S06.md
        #  - "Sujet 7" : Annales/Corriges/2022-S07.md
        #  - "Sujet 8" : Annales/Corriges/2022-S08.md
        #  - "Sujet 9" : Annales/Corriges/2022-S09.md
        #  - "Sujet 10" : Annales/Corriges/2022-S10.md
        #  - "Sujet 11" : Annales/Corriges/2022-S11.md
        #  - "Sujet 12" : Annales/Corriges/2022-S12.md
        #  - "Sujet 13" : Annales/Corriges/2022-S13.md
        #  - "Sujet 14" : Annales/Corriges/2022-S14.md
        #  - "Sujet 15" : Annales/Corriges/2022-S15.md
        #  - "Sujet 16" : Annales/Corriges/2022-S16.md
        #  - "Sujet 17" : Annales/Corriges/2022-S17.md
        #  - "Sujet 18" : Annales/Corriges/2022-S18.md
        #  - "Sujet 19" : Annales/Corriges/2022-S19.md
        #  - "Sujet 20" : Annales/Corriges/2022-S20.md
        #  - "Sujet 21" : Annales/Corriges/2022-S21.md
        #  - "Sujet 22" : Annales/Corriges/2022-S22.md
        #  - "Sujet 23" : Annales/Corriges/2022-S23.md
        #  - "Sujet 24" : Annales/Corriges/2022-S24.md
        #  - "Sujet 25" : Annales/Corriges/2022-S25.md
        #  - "Sujet 26" : Annales/Corriges/2022-S26.md
        #  - "Sujet 27" : Annales/Corriges/2022-S27.md
        #  - "Sujet 28" : Annales/Corriges/2022-S28.md
        #  - "Sujet 29" : Annales/Corriges/2022-S29.md
        #  - "Sujet 30" : Annales/Corriges/2022-S30.md
        #  - "Sujet 31" : Annales/Corriges/2022-S31.md
        #  - "Sujet 32" : Annales/Corriges/2022-S32.md
        #  - "Sujet 33" : Annales/Corriges/2022-S33.md
        #  - "Sujet 34" : Annales/Corriges/2022-S34.md
        #  - "Sujet 35" : Annales/Corriges/2022-S35.md
        #  - "Sujet 36" : Annales/Corriges/2022-S36.md
        #  - "Sujet 37" : Annales/Corriges/2022-S37.md
        #  - "Sujet 38" : Annales/Corriges/2022-S38.md
        #  - "Sujet 39" : Annales/Corriges/2022-S39.md
        #  - "Sujet 40" : Annales/Corriges/2022-S40.md

    - R√©vision Sujet BAC üìù :  
      - Acceuil BAC : BAC/index_BAC.md
      - Piles et Files : BAC/pile_file/compilation_pile_file.md
    #  - Consigne : divers/Consigne_EP.md
    #  - Sujets : divers/EpreuvePratique.md
      #- EP 2022 : BAC/EP_2022.md
  
    - Evaluations :
      - Index : progression.md
      - DS 0001 : Evaluations/BDD_Devoir_Corrige.md
      - DS 0011 : Evaluations/DS_Pile_File_Routage.md
      #- DS 0100 : Evaluations/DS_Diviser_pour_regner_tris.md
      - DS 0100 : Evaluations/DS0100bis.md
      - Eval EP1 : Evaluations/DS_EP1.md
      - Eval EP2 : Evaluations/DS_EP2.md
      - Eval EP3 : Evaluations/DS_EP3.md
      - DS 0101 : Evaluations/DS_Arbres.md


    - Extras :
      - Mini-Projet : Projet/pygame.md
      - Epreuve GEIPI : divers/sujet0_geipi.pdf
    - Divers conseils : divers/conseil.md

    


# D√©finition du th√®me https://squidfunk.github.io/mkdocs-material/creating-your-site/
theme:
    name: material
    custom_dir: overrides
    font: false  # RGPD ; pas de fonte Google
    language: fr # fran√ßais
    icon:
      logo: fontawesome/solid/spider
    favicon : images/dragon.svg

    palette: # Palettes de couleurs jour/nuit, cf : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
      - scheme: default # nom du th√®me clair
        primary: blue # couleur primaire des titres, des liens, ..., √† prendre dans la liste
        accent: blue # couleur d'accentuation au survol des boutons, desliens, ..., √† prendre dans la liste
        toggle: # d√©finition du bouton pour switcher de palette
          icon: material/lightbulb # apparence
          name: Basculer en mode sombre # message
      - scheme: slate # nom du th√®me sombre
        primary: blue
        accent: blue
        toggle:
          icon: material/lightbulb-outline
          name: Basculer en mode clair

    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - navigation.top
        - navigation.sections
        - navigation.indexes
        - navigation.tracking
        #- toc.integrate
        - header.autohide
        - content.code.annotate
     


markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    # extensions de la biblioth√®que markdown standard
    - abbr                          # infobulles sur abbr√©viations 
    - meta                          # M√©tadonn√©es
    - def_list                      # Les listes de d√©finition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - md_in_html                    # Pour √©crire en MarkDown dans des balises HTML https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs color√©s  !!! info "ma remarque"
    - toc: # Table des mati√®res
        permalink: ‚öìÔ∏é
        toc_depth: 3
    # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.details              #   qui peuvent se plier/d√©plier.
    - pymdownx.caret                # Passage ^^soulign√©^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surlign√©==.
    - pymdownx.tilde                # Passage ~~barr√©~~ ou en ~indice~.
    - pymdownx.highlight:            # Coloration syntaxique du code
        auto_title: true
        auto_title_map:
            "Python": "üêç Script Python"
            "Python Console Session": "üêç Console Python"
            "Text Only": "üìã Texte"
            "E-mail": "üì• Entr√©e"
            "Text Output": "üì§ Sortie"
            "SQL": "üóÇÔ∏è Requ√™te SQL"

    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases √† cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:               # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:  # Formules en LaTeX 
        generic: true



plugins:
  #- page-to-pdf : 
      #disable: False
      #disableOnServe: False
      #displayHeaderFooter: True
  #    printBackground: True
  #    scale : 1.0
  #    landscape : False
      #margin: {'top': '0.75cm', 'bottom': '0.75cm', 'right': '0.5cm','left': '0.5cm'}
  #    headerTemplate: '<header style="width:100%;heigth:45px;font-size:10px;font-weight:600;color:white;background:#A19162;margin-top:-20px;padding:10px;padding-bottom:0;-webkit-print-color-adjust: exact">
  #                     <span style="display:inline-block;vertical-align:middle;margin-top:-4px;margin-left:10px;">N.S.I : Terminale - 2022 - 2023</span>
  #                    </header>'
  #    footerTemplate: '<footer style="position:relative;width:100%;font-size:8px;color:#3B444B;margin:10px 20px;-webkit-print-color-adjust: exact">
  #                      <span>M.Meyroneinc-Condy | CCBY | 2021</span>
  #                      <span class="page" style="position:absolute;bottom:0;right:0;">
  #                       <span class="pageNumber"></span>/<span class="totalPages"></span>
  #                      </span>'
  - search # Inclure une barre de recherche
  - mkdocs-jupyter: # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
      kernel_name: python3
      execute: False
      include_source: True
  - macros
  - awesome-pages:
      collapse_single_pages: true
  #- mkpdfs:
  #    design: design/extra.css
  #- with-pdf:
      #author: M.Meyroneinc
      #copyright: ANY TEXT
      
      #cover: false
      #back_cover: true
      #cover_title: Cours Terminale NSI 2022 - 2023
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
        #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
  #- pdf-export:
      #combined: true

  #   headerTemplate : 
  #      title
  #      date
  #      pageNumber
  #      totalPages
  #    footerTemplate : True
  #      pageNumber
  #      totalPages
      




extra_javascript:
  - xtra/mathjax.js                    # MathJax
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/massilia-admonitions.js

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/css/massilia-admonitions.css
