# Fichier de configuration du site Ã  personnaliser

# Informations du site 
site_name: NSI Terminale 2023-2024
site_description: Cours et TD de l'annÃ©e en cours
#site_author: "Michael Meyroneinc-condy" 
#copyright: 2023 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a> 
site_url: 

# Structure des dossiers :
docs_dir: docs

# Menu de navigation
nav: 
    - Accueil : index.md
    #- Index : progression.md
    #- Test : Notebook.ipynb

    - T2 - Bases donnÃ©es :  
          - Base de donnÃ©es : T2_BasesDonnees/index_bd.md
          - ğŸ““ C1 ModÃ¨le relationnel : T2_BasesDonnees/Modele_Relationnel.md
          - ğŸ““ Memento Langage SQL : T2_BasesDonnees/memento_SQL.md
          #- ğŸ““ C2 Langage SQL : BasesDonnees/Cours_TP_SQL.md
          - ğŸ“ S2 BAC SQL : T2_BasesDonnees/SQL_BAC.md
          #- ğŸ“ S2 BAC SQL : T2_BasesDonnees/SQL_BAC_BIS.md
          #- ğŸ“ S2 BAC SQL Correction : BasesDonnees/SQL_BAC_correction.md
          
    - T3 - Struct. donnÃ©es :
      - Structures de donnÃ©es : StructureDonnees/index_structDonnees.md
      - ğŸ““ T3.1 P.O.O : T1_Structure_Donnees/POO.md
      - ğŸ““ S4 P.O.O BAC  :  T1_Structure_Donnees/POO_BAC.md
      #- ğŸ’» T4 POO Exercices : StructureDonnees/T1_2_TD_POO.md
      #- ğŸ’» TD POO BAC : StructureDonnees/T1_3_BAC_Capytale.md     
      #- ğŸ“ S4 Sujet POO BAC : StructureDonnees/POO_BAC_correction.md
      - ğŸ““ T3.2 Piles : T3_Structure_Donnees/Pile.md
      - ğŸ““ T3.3 Files : T3_Structure_Donnees/File.md
      - ğŸ““ T3.4 Arbres : T3_Structure_Donnees/Arbres.md
      #- T2_2 BAC - Listes, Piles et Files : StructureDonnees/T2_2_Pile_File_BAC.md
      #- ğŸ“ S5 BAC Correction - Listes, Piles et Files : StructureDonnees/T2_2_Pile_File_BAC_Correction.md
      #- ğŸ““ C9 Les dictionnaires : StructureDonnees/T4_1_Dictionnaires.md
      #- ğŸ““ C10 Les arbres : StructureDonnees/T3_1_arbre.md
      #- ğŸ“ S10 BAC Les arbres : StructureDonnees/T3_2_arbre_BAC.md
      #- Les Dictionnaires: StructureDonnees/T4_2_dictionnaires.md
      #- Les graphes : Graphe/TD_Graphe.md


    
    
    
    - T3 - Archi. mat. :
      - Architecture matÃ©rielle et OS : Archi_Materielle/index_archi.md
      #- ğŸ““ C5 Protocole de routage : Archi_Materielle/T3_1_Routage.md
      #- T3_1 BAC Protocole de routage : Archi_Materielle/T3_1_Routage_BAC.md
      #- ğŸ“ S6 BAC Correction Protocole de routage : Archi_Materielle/T3_1_Routage_BAC_Correction.md
      #- ğŸ““ C13 Gestion Processus : Archi_Materielle/T3_2_gestion_processus.md
      #- ğŸ“ S13 BAC Gestion Processus : Archi_Materielle/T3_3_gestion_processus_BAC.md
      #- ğŸ““ C21 SystÃ¨me sur puce : Archi_Materielle/T3_5_systeme_sur_puce.md
    
    - T4 - Prog. :
      - Programmation : Programmation/index_prog.md
      #- ğŸ““ C3 RÃ©cursivitÃ©  :  T5_Programmation/T4_1_Cours_TP_Recursivite_2023_2024_PROF.ipynb
      - ğŸ““ S4 POO BAC  :  T5_Programmation/POO_BAC.md

      #- CalculabilitÃ©, dÃ©cidabilitÃ© : Programmation/calculabilite.md
      
    #   - RÃ©cursivitÃ© : Programmation/T4_1_TP_Recursivite_correction.md

    - T5 Algo. : 
      - Algorithmique : Algo/index_algo.md
      #- ğŸ““ C7 Tri 1Ã¨re : Algo/T5_2_algo_tri.md
      #- ğŸ““ C8 Diviser pour rÃ©gner : Algo/T5_3_Diviser_pour_regner.md
      #- ğŸ“ S8 Diviser pour rÃ©gner BAC : Algo/T5_4_Diviser_pour_regner_BAC.md
      #- ğŸ““ C11 ImplÃ©mentation des arbres binaires : Algo/TP5_5_Implementation_arbres.md
      #- ğŸ“ S11 Algorithme arbres binaires BAC : Algo/T5_6_algo_arbre_BAC.md
      #- ğŸ““ C12 Arbres binaires de recherche : StructureDonnees/T3_3_arbre_recherche.md
      #- ğŸ“ S12 Arbres binaires de recherche BAC : StructureDonnees/T3_4_arbre_recherche_BAC.md
      #- k-plus proches voisins : Algo/TP6_1_kppv.md
      #- Les Graphes Cours : Graphe/Graphe.md
      #- Les Graphes Parcours : Graphe/TD_Graphe_Parcours.md
      #- Les Graphes Exercices : Graphe/TD_Graphe_Exercices.md

    - Mini-Projet : 
      - POO  mini-projet : Projet/POO_projet.md
    - BAC ğŸ“:
      - Information: BAC/bac_explication.md
      - '2023': 
        - "Epreuves Ã©crites" : Annales/2023/EE.md
      - '2022': 
        - "Epreuves Ã©crites" : Annales/2022/EE.md
      - '2021': 
        - "Epreuves Ã©crites" : Annales/2021/EE.md




    - Annales E.P. ğŸ’» :
      - DÃ©roulement : epreuve_pratique.md
      - Consigne : divers/Consigne_EP.md
      - S'entrainer en ligne pour l'Ã©preuve pratique: divers/lien.md

      #- index_annales.md
      #- '2022': 
      #  - "Epreuves pratiques" : Annales/2022/EP.md
      - '2023': 
        - "Epreuves pratiques" : Annales/2023/EP.md
        
    #- RÃ©vision BAC ğŸ“ :  
      #- Acceuil BAC : BAC/index_BAC.md
      #- Piles et Files : BAC/pile_file/compilation_pile_file.md
      #- RÃ©cursivitÃ© : BAC/recursivite/compile_recursivite.md
      #- Programmation Tableaux : BAC/programmation/compilation_programmation.md
      #- SQL : BAC/SQL/compile_sql.md
    #  - Consigne : divers/Consigne_EP.md
    #  - Sujets : divers/EpreuvePratique.md
      #- EP 2022 : BAC/EP_2022.md
  
    #- Devoirs :
    #  - Devoirs : Evaluations\index_eval.md
    #  - DS 1 : Evaluations\DS1_correction.md
    #- Grand Oral:
      #- Grand Oral : oral/oral.md

    - Eval. :
      - Index : progression.md
      - DS 1 : Evaluations/DS1_correction.md
      - DS 2 : Evaluations/DS2_correction.md
      #- DS 0011 : Evaluations/DS_Pile_File_Routage.md
      #- DS 0100 : Evaluations/DS_Diviser_pour_regner_tris.md
      #- DS 0100 : Evaluations/DS0100bis.md
      #- Eval EP1 : Evaluations/DS_EP1.md
      #- Eval EP2 : Evaluations/DS_EP2.md
      #- Eval EP3 : Evaluations/DS_EP3.md
      #- DS 0101 : Evaluations/DS_Arbres.md
      #- Eval EP4 : Evaluations/DS_EP4.md
      #- Eval EP5 : Evaluations/DS_EP5.md
      #- Eval EP6 : Evaluations/DS_EP6.md
      #- Eval EP7 : Evaluations/DS_EP7.md
      #- DS 0110 : Evaluations/DS0110.md
    
    - Extras :
      - Divers concours programmation: divers/prog.md
      #- Force brute : Projet/forcebrute.md
      #- Cryptographie: Projet/cryptographie.md
      #- Cryptographie bis: Projet/cryptographie2.md
      #- pyxel: Projet/pyxel.md
      #- Life & Death : Projet/life_and_death.md
      #- Mini-Projet : Projet/pygame.md
      #- Epreuve GEIPI : divers/sujet0_geipi.pdf
    
    - CrÃ©dits : credit.md
    #- Divers conseils : divers/conseil.md
    

    


# DÃ©finition du thÃ¨me https://squidfunk.github.io/mkdocs-material/creating-your-site/
theme:
    name: material
    custom_dir: overrides
    font: false  # RGPD ; pas de fonte Google
    language: fr # franÃ§ais
    icon:
      logo: fontawesome/solid/dragon
    favicon : images/dragon.svg

    palette: # Palettes de couleurs jour/nuit, cf : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
      - scheme: default # nom du thÃ¨me clair
        primary: blue # couleur primaire des titres, des liens, ..., Ã  prendre dans la liste
        accent: blue # couleur d'accentuation au survol des boutons, desliens, ..., Ã  prendre dans la liste
        toggle: # dÃ©finition du bouton pour switcher de palette
          icon: material/lightbulb # apparence
          name: Basculer en mode sombre # message
      - scheme: slate # nom du thÃ¨me sombre
        primary: blue
        accent: blue
        toggle:
          icon: material/lightbulb-outline
          name: Basculer en mode clair

    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - navigation.top
        - navigation.sections
        - navigation.indexes
        - navigation.tracking
        #- toc.integrate
        - header.autohide
        - content.code.annotate
     


markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    # extensions de la bibliothÃ¨que markdown standard
    - abbr                          # infobulles sur abbrÃ©viations 
    - meta                          # MÃ©tadonnÃ©es
    - def_list                      # Les listes de dÃ©finition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - md_in_html                    # Pour Ã©crire en MarkDown dans des balises HTML https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorÃ©s  !!! info "ma remarque"
    - toc: # Table des matiÃ¨res
        permalink: âš“ï¸ 
        toc_depth: 3
    # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.details              #   qui peuvent se plier/dÃ©plier.
    - pymdownx.caret                # Passage ^^soulignÃ©^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surlignÃ©==.
    - pymdownx.tilde                # Passage ~~barrÃ©~~ ou en ~indice~.
    - pymdownx.highlight:            # Coloration syntaxique du code
        auto_title: true
        auto_title_map:
            "Python": "ğŸ Script Python"
            "Python Console Session": "ğŸ Console Python"
            "Text Only": "ğŸ“‹ Texte"
            "E-mail": "ğŸ“¥ EntrÃ©e"
            "Text Output": "ğŸ“¤ Sortie"
            "SQL": "ğŸ—‚ï¸ RequÃªte SQL"

    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases Ã  cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:               # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:  # Formules en LaTeX 
        generic: true



plugins:
  #- page-to-pdf : 
  #    disable: False
  #    disableOnServe: False
  #    displayHeaderFooter: True
  #    printBackground: True
  #    scale : 1.0
  #    landscape : False
  #    margin: {'top': '0.75cm', 'bottom': '0.75cm', 'right': '0.5cm','left': '0.5cm'}
  #    headerTemplate: '<header style="width:100%;heigth:45px;font-size:10px;font-weight:600;color:white;background:#A19162;margin-top:-20px;padding:10px;padding-bottom:0;-webkit-print-color-adjust: exact">
  #                     <span style="display:inline-block;vertical-align:middle;margin-top:-4px;margin-left:10px;">N.S.I : Terminale - 2023 - 2024</span>
  #                    </header>'
  #    footerTemplate: '<footer style="position:relative;width:100%;font-size:8px;color:#3B444B;margin:10px 20px;-webkit-print-color-adjust: exact">
  #                      <span>M.Meyroneinc-Condy | CCBY | 2023</span>
  #                      <span class="page" style="position:absolute;bottom:0;right:0;">
  #                       <span class="pageNumber"></span>/<span class="totalPages"></span>
  #                      </span>'
  - search # Inclure une barre de recherche
  #- mkdocs-jupyter # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
  #    kernel_name: python3
  #    execute: False
  #    include_source: True
  - macros
  - awesome-pages:
      collapse_single_pages: true
  #- mkpdfs:
  #    design: design/extra.css
  #- with-pdf:
      #author: M.Meyroneinc
      #copyright: ANY TEXT
      
      #cover: false
      #back_cover: true
      #cover_title: Cours Terminale NSI 2022 - 2023
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
        #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
  #- pdf-export:
  #    verbose: true
  #    media_type: print
      #enabled_if_env: ENABLE_PDF_EXPORT
      #combined: true

  #   headerTemplate : 
  #      title
  #      date
  #      pageNumber
  #      totalPages
  #    footerTemplate : True
  #      pageNumber
  #      totalPages
      




extra_javascript:
  - xtra/mathjax.js                    # MathJax
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/massilia-admonitions.js

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/css/massilia-admonitions.css
